defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:4.8
      - image: circleci/golang:1.8

    steps:
      - attach_workspace:
          at: /tmp

      - checkout

      - run:
          name: Install ghr
          command: |
            go get github.com/tcnksm/ghr

      - run:
          name: Publish assets
          command: |
            ghr

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?-custom$/
